//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlipperProduction.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AmountColorSlippes { get; set; }
        public Nullable<int> AmountOrdinarySlippes { get; set; }
        public Nullable<bool> DoneOrNot { get; set; }
        public Nullable<int> ID_Employee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
