//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlipperProduction.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slipper
    {
        public int ID { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<int> ID_Type { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
